### ISSUE TITLE
User Found action violates strictActionSerializability NgRx 8 runtime check

### ISSUE THREAD

**Issue by joe-mills** [sourcenetwork/ng-oidc-client#12]
**Describe the bug**

The OidcUser payload violates the new strictActionSerializability check in NgRx 8

```
export class UserFound implements Action {
  readonly type = OidcActionTypes.UserFound;

  constructor(public payload: OidcUser) {}
}
```

**To Reproduce**
1. Update to NgRx 8
2. Enable runtime  checks

```
@NgModule({
  imports: [
    StoreModule.forRoot(reducers, {
      runtimeChecks: {
        strictStateImmutability: true,
        strictActionImmutability: true,
        strictStateSerializability: true,
        strictActionSerializability: true,
      },
    }),
  ],
})
```
3. Login and call this.oidcFacade.getOidcUser();
4. Console log shows error
core.js:5847 ERROR Error: Detected unserializable action at "payload"

**Expected behavior**
[Oidc] User found action should complete without runtime error

**Desktop (please complete the following information):**
 - Windows 10
 - Browser chrome 
 - Version 74

**Comment by alx-andru** [comment]
Thanks for reporting the issue. Will try to update NgRx within the next couple weeks.

**Comment by MichielVanderlee** [comment]
Any progress on this?

**Comment by david-on-github** [comment]
@mvanderlee 
This has been implemented in the latest version. 
Let me know if you still have any issues.
