### ISSUE TITLE
ResponseValidator._processSigninParams: Expecting code in response

### ISSUE THREAD

**Issue by akshay234** [sourcenetwork/ng-oidc-client#13]
**Describe the bug**
ResponseValidator._processSigninParams: Expecting code in response

i get problem in function of signinRedirectCallback that function throws Expecting code in response like error.. below is my configuration for OIDC in app.module.ts file

NgOidcClientModule.forRoot({
      oidc_config: {
        authority:
          'http://172.16.23.104:4444',
        client_id: 'js',
        redirect_uri: 'http://localhost:4200/callback.html',
        response_type: 'code',
        scope: 'openid profile positions',
        post_logout_redirect_uri:
          'http://localhost:4200/signout-callback.html',
        silent_redirect_uri: 'http://localhost:4200/renew-callback.html',
        acr_values: 'tenant:EDF',
        userStore: () => new WebStorageStateStore({store: localStorage}),
      }
    }),
and in login i simply call:- this.oidcFacade.signinRedirect();

and in callback.html file 

<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />
  <title>Callback</title>
  <link rel="icon"
        type="image/x-icon"
        href="favicon.png">
  <script src="oidc-client.min.js"
          type="application/javascript"></script>
</head>

<body>
  <script>
    var Oidc = window.Oidc;
 
    var config = {
      userStore: new Oidc.WebStorageStateStore({ store: window.localStorage })
    }

 if ((Oidc && Oidc.Log && Oidc.Log.logger)) {
   Oidc.Log.logger = console;
 }
 var isPopupCallback = JSON.parse(window.localStorage.getItem('ngoidc:isPopupCallback'));
 if (isPopupCallback) {
   new Oidc.UserManager(config).signinPopupCallback();
 } else {
   new Oidc.UserManager(config).signinRedirectCallback().then(t => {
     window.location = 'http://localhost:4200';
   }).catch((e) => {
     console.log(e);
   });
 }
  </script>
</body>

</html>

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser chrome

**Comment by david-on-github** [comment]
Hi,
You'll need to modify the configuration to include the `query` response mode in the callback when using authorization code flow.


```javascript
var config = {
    response_mode:'query',
    userStore: new Oidc.WebStorageStateStore({ store: window.localStorage })
}
```

See code flow examples here:
https://github.com/IdentityModel/oidc-client-js/blob/dev/samples/VanillaJS/public/code-identityserver-sample-callback.js

Let me know if this solves your issue.

**Comment by akshay234** [comment]
Yes now it is working but one more issue if i am refresh angular app localstorage is removed.
