### ISSUE TITLE
Strange import from @angular/core

### ISSUE THREAD

**Issue by malled** [sourcenetwork/ng-oidc-client#17]
Hello,
I've encountered a problem when using this library through npm.

The file `node_modules\ng-oidc-client\fesm5\ng-oidc-client.js` contains the following import:

`import { InjectionToken, Injectable, Inject, PLATFORM_ID, ɵɵdefineInjectable, ɵɵinject, NgModule } from '@angular/core';`

It throws several warnings like the one below when building:
```
WARNING in C:/Code/ocCore/Clients/angular/node_modules/ng-oidc-client/fesm5/ng-oidc-client.js 620:53-71
"export 'ɵɵdefineInjectable' was not found in '@angular/core'
```

This char is wrong: `ɵɵ`. If you remove it, everything works as expected. 

Why does the file contain that char? Wrong code published to npm?

packages:
```
"@angular/core": "^7.2.15",
"ng-oidc-client": "^1.0.6",
"oidc-client": "^1.9.1",
```

**Comment by malled** [comment]
@alx-andru @david-on-github may you have a look at it? anything unclear?

**Comment by alx-andru** [comment]
hey @malled we've seen a few issues now with the latest updates of packages. I'll try to look into it with a more solid solution over the next week or two.

**Comment by malled** [comment]
Same appears when building the module locally; therefore it's not a npm issue

**Comment by david-on-github** [comment]
Backward compatibility issue with ng8. We need to revert packages back to compile using 7. 
Then release a new version for 8.
