### ISSUE TITLE
Popup authentication is working but redirect one is failing

### ISSUE THREAD

**Issue by aakash1401** [sourcenetwork/ng-oidc-client#19]
**Describe the bug**

First, thank you for amazing library. I have cloned the library locally, replaced oidc_config with my server details. Everything is good. I even checked the code with dummy server online i.e. https://demo.identityserver.io. It is working fine for Popup flow but it is giving error/failing during redirect flow.

**To Reproduce**

1. Just clone/download the ng-oidc-client code and run with your own configuration.
2. Run the application on localhost. If you click on the Redirect button, it should redirect to the authentication server.
3. The user sees the blank screen with localhost callback in the URL but somehow fails to return to the home screen. Please see the attached images:

<img width="958" alt="Consoler error" src="https://user-images.githubusercontent.com/31201591/67075083-145dc480-f1a8-11e9-87d8-30c11d818d4b.PNG">

**Expected behavior**
The application should redirect to localhost after authentication without error like it is working for a popup.

**Screenshots**

<img width="938" alt="Screenshot OIDC" src="https://user-images.githubusercontent.com/31201591/67075453-cb5a4000-f1a8-11e9-84b9-f205b60570d8.PNG">

**Desktop (please complete the following information):**
Any

**Additional context**
What could be the issue? Does it require some fix from the code side? Please help.

**Comment by malled** [comment]
I'm facing the same issue. 
On callback.html page, the library cannot find the right settings. Because of this, it tries to load the user from local storage with an undefined key `user:undefined:undefined`.

How is it supposed to work? When the login flow starts, the right settings are added to local storage with a prefix + id, but how should the callback know the id and where does it get parsed?

**Comment by david-on-github** [comment]
Hi @malled ,

It's been a while, but from what I remember that shouldn't be necessary. The user loaded event should be caught in oidc-client which loads the user into state. Looks like the signinPopup effect doesn't load a user even though it recieves it in the promise, and I believe we did that to prevent over dispatching duplicate actions.
