### ISSUE TITLE
How to resend failed requests from httpInterceptor upon renewing token asynchronously

### ISSUE THREAD

**Issue by mbnwabtec** [sourcenetwork/ng-oidc-client#22]
Hi, your help is greatly appreciated. 

I am struck in finding a way to resend failed requests (401 unauthorized) captured while renewing token (silent refresh) through httpInterceptor. 

I have httpInteceptor in place to attach bearer token to all outgoing web requests. When the token is expired, I get 401 unauthorized response from web server. I am catching these unauthorized request/responses and requesting for renewing token through silentSignin method from ng-oidc-client. 

Silent renewal is happening through asynchronous call. I am not sure on how to resend failed requests with the renewed token. Any help on this is highly valuable for me. I tried re sending failed requests through setTimeOut, unfortunately requests are not getting captured under network tab.

**Comment by david-on-github** [comment]
Closing as not really a bug.

But basically you will need to find a way to capture and queue up the in-flight requests after a 401 is encountered and either retry in the event a new token is received or pass them through in the event it failed. However, if you use the oidc-client-js automatic renew option, you shouldn't encounter this issue as the token will renew before expiry.
