### ISSUE TITLE
Angular 9 - authenticated user not loaded

### ISSUE THREAD

**Issue by buzzbonner** [sourcenetwork/ng-oidc-client#28]
**Describe the bug**

**To Reproduce**
1. Implement Router guard. In CanActivate()

return this.oidcFacade.waitForAuthenticationLoaded().pipe(
      switchMap(() => {
        return this.oidcFacade.identity$.pipe(

2. Start application from url with implicit authentication via guard
3. No user loaded

**Expected behavior**

This was fine in Angular 8, but no longer working in Angular 9?

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 80.0.3987.132

**Additional context**

Does the product support Angular 9?

**Comment by 839928622** [comment]
does this library works on Angular 9 ?

**Comment by david-on-github** [comment]
It should, can you provide more details.

It's not very clear in the docs but a call needs to be made to the facade service `getOidcUser()` method somewhere to check if the user is in storage. This could be done in the entry route, a parent route, a service, a guard, etc. Depends on the requirements of your app.

**Comment by 839928622** [comment]
> It should, can you provide more details.
> 
> It's not very clear in the docs but a call needs to be made to the facade service `getOidcUser()` method somewhere to check if the user is in storage. This could be done in the entry route, a parent route, a service, a guard, etc. Depends on the requirements of your app.

 I copy  following blocks code,it did't work,when console.log('Auth Guard - Checking if user exists', user)，it shows null on console ,but I actualy can see the user access_token and profile in localstorage,did I miss something importent?
those are a couple of code that I copyed :
export class OidcGuardService implements CanActivate {
  constructor(private router: Router, private oidcFacade: OidcFacade) {}

  public canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): Observable<boolean> | boolean {
    return this.oidcFacade.identity$.pipe(
      take(1),
      switchMap(user => {
        console.log('Auth Guard - Checking if user exists', user);
        console.log('Auth Guard - Checking if user is expired:', user && user.expired);
        if (user && !user.expired) {
          return of(true);
        } else {
          this.router.navigate(['/login']);
          return of(false);
        }
      })
    );
  }
}

**Comment by 839928622** [comment]
> It should, can you provide more details.
> 
> It's not very clear in the docs but a call needs to be made to the facade service `getOidcUser()` method somewhere to check if the user is in storage. This could be done in the entry route, a parent route, a service, a guard, etc. Depends on the requirements of your app.

 I copy  following blocks code,it did't work,when console.log('Auth Guard - Checking if user exists', user)，it shows null on console ,but I actualy can see the user access_token and profile in localstorage,did I miss something importent?
those are a couple of code that I copyed :
export class OidcGuardService implements CanActivate {
  constructor(private router: Router, private oidcFacade: OidcFacade) {}

  public canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): Observable<boolean> | boolean {
    return this.oidcFacade.identity$.pipe(
      take(1),
      switchMap(user => {
        console.log('Auth Guard - Checking if user exists', user);
        console.log('Auth Guard - Checking if user is expired:', user && user.expired);
        if (user && !user.expired) {
          return of(true);
        } else {
          this.router.navigate(['/login']);
          return of(false);
        }
      })
    );
  }
}

**Comment by david-on-github** [comment]
`GetOidcUser()` should be called before trying to access `identity$` if you are expecting a value for identity. This dispatches an event to retrieve and set the property. This should be done prior to checking in an auth guard. 

`identity$` just returns the current value of the identity in the store as observable. Whether it was set or not.

`GetOidcUser()` will look into the cache and set the user if one exists. It also sets the loading flag while it resolves it.

`waitForAuthenticationLoaded()` is just a function for waiting until the loading flag becomes false, if not already.

**Comment by 839928622** [comment]
I enject OidcFacade to AuthGuarad,and call `this.oidcFacade.GetOidcUser()`,still can not retrieve user access_token and profile ,when I flick back to localstorage ,I can see user access_token and pfofile. 
you can check my source code on :
[https://github.com/839928622/ERP-Angular-WebApp/blob/master/src/app/Guards/auth.guard.ts](url)
line 14

**Comment by Alex-Torres** [comment]
I think the issue may be related to where you may be pulling user information Local or Session Storage.  I think the library by default pulls from Session Storage.  When I updated the CallBack.html: 

userStore: new Oidc.WebStorageStateStore({ store: window.**sessionStorage** }),

I started to see user information and the selector updated.

**Comment by david-on-github** [comment]
Please provide repro if this is still an issue. Thanks
