### ISSUE TITLE
Use Angular's components for Callbacks instead of static HTML files?

### ISSUE THREAD

**Issue by mdmoura** [sourcenetwork/ng-oidc-client#30]
On your docs you use HTML files for callbacks: 

```
src/static
├── callback.html
├── renew-callback.html
└── signout-callback.html
```

Can't Angular components be uses instead of static HTML files?

Why use HTML files?

**Comment by david-on-github** [comment]
Hi @mdmoura. We had some issues with angular router dropping the hash fragment before we could eventually read it in the component.

But yes, It's probably possible to configure the callbacks to routes.
