### ISSUE TITLE
Requests get refired after token refresh

### ISSUE THREAD

**Issue by luukhaijes** [sourcenetwork/ng-oidc-client#32]
**Describe the bug**
When the token gets refreshed all previous requests are fired again.
The request is a normal HTTP call, nothing fancy.

**Expected behavior**
The token call is the only call that's made

**Screenshots**
As you see, a few requests get refired and get cancelled.
<img width="1318" alt="image" src="https://user-images.githubusercontent.com/12485595/86731918-419d1c00-c030-11ea-962e-4d20f6c2377e.png">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: All
 - Version: current version version of package, Angular 9

This bug could also come from the OIDC-Client package but i'm not sure.

**Comment by luukhaijes** [comment]
Okay, tried a few things and I added take(1) to the identity$ pipe.
![image](https://user-images.githubusercontent.com/12485595/86796683-21408200-c06f-11ea-8119-1208e717cb25.png)

**Comment by david-on-github** [comment]
Hey @luukhaijes ,

Perfectly valid. `identity$` is a long running observable. 
So you will want to terminate it.

**Comment by david-on-github** [comment]
Updated in readme, Thanks
bd5d373e67e7a30bd5f6f7a24d813fc198872d06
