### ISSUE TITLE
Update dependencies to reflect Angular 7.x

### ISSUE THREAD

**Issue by alx-andru** [sourcenetwork/ng-oidc-client#8]

**Comment by alalca** [comment]
Please keep in mind update the peerDependencies.

"peerDependencies": {
    "@angular/common": "^6.0.0-rc.0 || ^6.0.0",
    "@angular/core": "^6.0.0-rc.0 || ^6.0.0"
  },

Thank you

**Comment by maclonghorn** [comment]
@alalca @alx-andru  Why are these dependencies for Angular 7?  This seems to be for Angular 6.

**Comment by alalca** [comment]
> @alalca @alx-andru Why are these dependencies for Angular 7? This seems to be for Angular 6.

Only @alx-andru knows! 😄

**Comment by alx-andru** [comment]
It is intended to just update the packages in general and reflect the most current angular releases. 
Due to angular 8 there might be some more changes upcoming, hence closing this old issue.
